# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  subscriptionEndpoint: 'AzurePaidSC2'
  imageName: 'springrestapp'
  containerRegistry: 'myregfaisal.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps: 
- task: Docker@1
  displayName: Build docker image
  inputs:
    command: Build an image
    dockerFile: $(dockerfilePath)
    imageName: $(imageName)
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(subscriptionEndpoint)
    azureContainerRegistry: $(containerRegistry)
    tags: |
          $(tag)
- task: Docker@1
  displayName: Push Docker image
  inputs:
    command: Push an image
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(subscriptionEndpoint)
    azureContainerRegistry: $(containerRegistry)
    imageName: $(imageName)
    tags: |
          $(tag)
