# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  registryConnection: 'acrConnection'
  imageRepository: 'springrestapp'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildNumber)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps: 
- task: Docker@2
  displayName: Build docker image
  inputs:
    command: build
    containerRegistry: $(registryConnection)
    repository: $(imageRepository)
    dockerFile: $(dockerfilePath)
    tags: $(tag)
- task: Docker@2
  displayName: Push Docker image
  inputs:
    command: push
    containerRegistry: $(registryConnection)
    repository: $(imageRepository)
    tags: $(tag)
